name: Deploy Epoch Forgotten client to Pages

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  # allows to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (production or stage)'
        required: true
        default: ':production'
        type: choice
        options:
          - :production
          - :stage

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install client dependencies
        run: yarn install

      - name: Clone server repository
        uses: actions/checkout@v4
        with:
          repository: epoch-dev/epoch-forgotten
          path: server
          ref: main
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install server dependencies
        run: yarn install
        working-directory: ./server

      - name: Generate client
        run: yarn gen-api && yarn gen-client
        working-directory: ./server

      - name: Copy generated client to frontend
        run: cp -r ./server/.generated ./src/common/api/

      - name: Build client
        run: yarn build${{ inputs.environment }}

      - name: Cache dist folder
        if: github.event_name == 'push'
        uses: actions/cache@v4
        with:
          path: ./dist
          key: ${{ runner.os }}-dist-${{ github.sha }}

  deploy:
    needs: build
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Restore dist folder from cache
        uses: actions/cache@v4
        with:
          path: ./dist
          key: ${{ runner.os }}-dist-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-dist-

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
